assign:
  strategy:
    # random
    daily-shift-based
  schedule:
    '*/1 * * * *'
  assignees:
    - myownskyW7
    - panzhang0212
    - yhcao6
    - LightDXY
    - myownskyW7
    - myownskyW7
    - myownskyW7
